### ISSUE TITLE
panic: runtime error: slice bounds out of range [:16393] with capacity 947

### ISSUE THREAD

**Issue by ruigyang-wish** [vearne/grpcreplay#18]
I encountered error `slice bounds out of range` on Linux Debian, it seems the logic of calculating payload length contains some error.

```
~/grpcreplay# ./grpcr --input-raw="0.0.0.0:9000" --output-stdout

   ______ ____   ____   ______ ____
  / ____// __ \ / __ \ / ____// __ \
 / / __ / /_/ // /_/ // /    / /_/ /
/ /_/ // _, _// ____// /___ / _, _/
\____//_/ |_|/_/     \____//_/ |_|
2024/07/18 23:55:02 [info] input-raw, [0.0.0.0:9000]
2024/07/18 23:55:02 [info] input-file-directory, []
2024/07/18 23:55:02 [info] input-file-replay-speed, 1
2024/07/18 23:55:02 [info] input-rocketmq-name-server, []
2024/07/18 23:55:02 [info] input-rocketmq-topic, test
2024/07/18 23:55:02 [info] output-stdout, true
2024/07/18 23:55:02 [info] output-file-directory, []
2024/07/18 23:55:02 [info] output-grpc, []
2024/07/18 23:55:02 [info] output-rocketmq-name-server, []
2024/07/18 23:55:02 [info] output-rocketmq-topic, test
2024/07/18 23:55:02 [debug] options: "0.0.0.0:9000"
2024/07/18 23:55:02 [debug] address:"0.0.0.0:9000"
2024/07/18 23:55:02 [info] create new Processer
2024/07/18 23:55:02 [info] ipSet:[127.0.0.1 10.34.7.125]
2024/07/18 23:55:02 [debug] NewStdOutput
2024/07/18 23:55:02 [info] plugins:#####  len(Inputs):1, len(Outputs):1, len(All):2   #####
2024/07/18 23:55:02 [debug] RAWInput.Listen()
2024/07/18 23:55:02 [debug] history connections:
2024/07/18 23:55:02 [debug] len(i.listenerList):2
2024/07/18 23:55:02 [info] All history connections has exited.
2024/07/18 23:55:02 [info] listener:device:eth0, port:9000, filter:tcp and port 9000
2024/07/18 23:55:02 [info] listener:device:lo, port:9000, filter:tcp and port 9000
2024/07/18 23:55:03 [debug] DeviceListener.listen-connection:10.34.7.125:9000 -> 10.34.38.22:45904, Direction:DirIncoming
2024/07/18 23:55:03 [debug] DeviceListener.listen-connection:10.34.7.125:9000 -> 10.34.11.162:38058, Direction:DirIncoming
2024/07/18 23:55:03 [debug] DeviceListener.listen-connection:10.34.7.125:9000 -> 10.34.16.45:34396, Direction:DirIncoming
2024/07/18 23:55:03 [debug] DeviceListener.listen-connection:10.34.7.125:9000 -> 10.34.16.45:34396, Direction:DirIncoming
2024/07/18 23:55:03 [debug] DeviceListener.listen-connection:10.34.7.125:9000 -> 10.34.16.45:34396, Direction:DirIncoming
2024/07/18 23:55:03 [debug] DeviceListener.listen-connection:10.34.7.125:9000 -> 10.34.16.45:34396, Direction:DirIncoming
2024/07/18 23:55:03 [debug] DeviceListener.listen-connection:10.34.7.125:9000 -> 10.34.16.45:34396, Direction:DirIncoming
2024/07/18 23:55:03 [debug] DeviceListener.listen-connection:10.34.7.125:9000 -> 10.34.16.45:34396, Direction:DirIncoming
2024/07/18 23:55:03 [debug] DeviceListener.listen-connection:10.34.7.125:9000 -> 10.34.16.45:34396, Direction:DirIncoming
2024/07/18 23:55:03 [debug] DeviceListener.listen-connection:10.34.7.125:9000 -> 10.34.16.45:34396, Direction:DirIncoming
2024/07/18 23:55:03 [debug] DeviceListener.listen-connection:10.34.7.125:9000 -> 10.34.16.45:34396, Direction:DirIncoming
2024/07/18 23:55:03 [debug] DeviceListener.listen-connection:10.34.7.125:9000 -> 10.34.16.45:34396, Direction:DirIncoming
2024/07/18 23:55:03 [debug] DeviceListener.listen-connection:10.34.7.125:9000 -> 10.34.16.45:34396, Direction:DirIncoming
2024/07/18 23:55:03 [debug] DeviceListener.listen-connection:10.34.7.125:9000 -> 10.34.16.45:34396, Direction:DirIncoming
2024/07/18 23:55:03 [debug] DeviceListener.listen-connection:10.34.7.125:9000 -> 10.34.16.45:34396, Direction:DirIncoming
2024/07/18 23:55:03 [debug] DeviceListener.listen-connection:10.34.16.45:34396 -> 10.34.7.125:9000, Direction:DirIncoming
2024/07/18 23:55:03 [debug] DeviceListener.listen-connection:10.34.16.45:34396 -> 10.34.7.125:9000, Direction:DirIncoming
2024/07/18 23:55:03 [debug] Connection:10.34.7.125:9000 -> 10.34.16.45:34396, seq:3231000168, FrameType:FrameHeader, length:2, streamID:2983
2024/07/18 23:55:03 [info] create Http2Conn, MaxDynamicTableSize:4096
2024/07/18 23:55:03 [debug] DeviceListener.listen-connection:10.34.16.45:34396 -> 10.34.7.125:9000, Direction:DirIncoming
2024/07/18 23:55:03 [debug] DeviceListener.listen-connection:10.34.16.45:34396 -> 10.34.7.125:9000, Direction:DirIncoming
2024/07/18 23:55:03 [debug] DeviceListener.listen-connection:10.34.16.45:34396 -> 10.34.7.125:9000, Direction:DirIncoming
2024/07/18 23:55:03 [debug] DeviceListener.listen-connection:10.34.16.45:34396 -> 10.34.7.125:9000, Direction:DirIncoming
2024/07/18 23:55:03 [debug] Padded:false, len(f.Payload):2, PadLength:0, len(HeaderBlockFragment):2
2024/07/18 23:55:03 [debug] DeviceListener.listen-connection:10.34.7.125:9000 -> 10.34.16.45:34396, Direction:DirIncoming
2024/07/18 23:55:03 [debug] DeviceListener.listen-connection:10.34.7.125:9000 -> 10.34.16.45:34396, Direction:DirIncoming
2024/07/18 23:55:03 [debug] Connection:10.34.7.125:9000 -> 10.34.16.45:34396, stream:2983, EndHeader:true, EndStream:false, MaxDynamicTableSize:4096
2024/07/18 23:55:03 [debug] DeviceListener.listen-connection:10.34.7.125:9000 -> 10.34.11.162:38058, Direction:DirIncoming
2024/07/18 23:55:03 [debug] DeviceListener.listen-connection:10.34.7.125:9000 -> 10.34.11.162:38058, Direction:DirIncoming
2024/07/18 23:55:03 [debug] DeviceListener.listen-connection:10.34.7.125:9000 -> 10.34.11.162:38058, Direction:DirIncoming
2024/07/18 23:55:03 [error] decoding error: invalid indexed representation index 64
2024/07/18 23:55:03 [debug] DeviceListener.listen-connection:10.34.16.45:34396 -> 10.34.7.125:9000, Direction:DirIncoming
2024/07/18 23:55:03 [debug] DeviceListener.listen-connection:10.34.7.125:9000 -> 10.34.11.162:38058, Direction:DirIncoming
2024/07/18 23:55:03 [debug] DeviceListener.listen-connection:10.34.7.125:9000 -> 10.34.11.162:38058, Direction:DirIncoming
2024/07/18 23:55:03 [debug] DeviceListener.listen-connection:10.34.11.162:38058 -> 10.34.7.125:9000, Direction:DirIncoming
panic: runtime error: slice bounds out of range [:16393] with capacity 947

goroutine 19 [running]:
github.com/vearne/grpcreplay/http2.ParseFrameBase({0xc0000bcc4d, 0x3b3, 0x3b3})
	/root/grpcreplay/http2/http2.go:208 +0x251
github.com/vearne/grpcreplay/http2.(*Processor).ProcessTCPPkg(0xc00007eca0)
	/root/grpcreplay/http2/processor.go:56 +0x14b
created by github.com/vearne/grpcreplay/plugin.NewRAWInput in goroutine 1
	/root/grpcreplay/plugin/input_raw.go:180 +0x7bd
```

**Comment by ruigyang-wish** [comment]
@vearne 
Thanks for your response. What information do you need for the triage?

**Comment by ruigyang-wish** [comment]
> Can you give me a complete example? @ruigyang-wish I suspect that port 9000 is not a grpc service, or that this service uses TLS
> 
> ```
> 	err = binary.Read(reader, binary.BigEndian, &fb.StreamID)
> 	if err != nil {
> 		return nil, err
> 	}
> 	fb.Payload = b[HeaderSize : HeaderSize+fb.Length]
> 	return &fb, nil
> ```

I have used the command `tcpflow -p -c -i eth0 port 9000` to captures the data transmitted through that port.
From the response, I can ensure that there is one grpc service which is listening on 9000.

**Comment by vearne** [comment]
If you can provide a minimal prototype of the grpc service, I can investigate the cause of the bug. The only situation I can think of is that the grpc request is too large and exceeds the size of a single TCP packet, but this seems unlikely in real life.

**Comment by ruigyang-wish** [comment]
@vearne 
Thanks, I write one new gRPC client to do this.

**Comment by vearne** [comment]
@ruigyang-wish  The bug has been fixed. You can download the latest code and rebuild the bin file. Thank you for your bug report.
